// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'
import '@/components/polyfill/Intl'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'es'
	| 'en'
	| 'zh'
	| 'ru'
	| 'fr'
	| 'de'
	| 'it'
	| 'ar'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
  SEARCH: string,
	/**
	 * Tab: Dashboard (Deprecated)
	 */
  DASHBOARD: string,
	/**
	 * Tab: Home
	 */
  HOME: string,
	/**
	 * Tab: Menu
	 */
  MENU: string,
	/**
	 * Navigation Bar: Back button
	 */
  BACK: string,
	/**
	 * Button: Sign In
	 */
  SIGNIN: string,
	/**
	 * Button: Sign Out
	 */
  SIGNOUT: string,
	/**
	 * Menu: Setting
	 */
  SETTINGS: string,
	/**
	 * Menu: Setting - Languages
	 */
  COUNTRYANDLANAGUAGE: string,
	/**
	 * Menu: Setting - Currencies
	 */
  CURRENCY: string
}

export type TranslationFunctions = {
  SEARCH: () => LocalizedString,
	/**
	 * Tab: Dashboard (Deprecated)
	 */
  DASHBOARD: () => LocalizedString,
	/**
	 * Tab: Dashboard
	 */
  HOME: () => LocalizedString,
	/**
	 * Tab: Menu
	 */
  MENU: () => LocalizedString,
	/**
	 * Navigation Bar: Back button
	 */
  BACK: () => LocalizedString,
	/**
	 * Button: Sign In
	 */
  SIGNIN: () => LocalizedString,
	/**
	 * Button: Sign Out
	 */
  SIGNOUT: () => LocalizedString,
	/**
	 * Menu: Setting
	 */
  SETTINGS: () => LocalizedString,
	/**
	 * Menu: Setting - Languages
	 */
  COUNTRYANDLANAGUAGE: () => LocalizedString,
	/**
	 * Menu: Setting - Currencies
	 */
  CURRENCY: () => LocalizedString
}

export type Formatters = {
	weekday: (value: Date) => unknown
}
