// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'es'
	| 'en'
	| 'zh'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * c​h​o​o​s​e​ ​l​o​c​a​l​e​.​.​.
	 */
	CHOOSE_LOCALE: string
	/**
	 * H​e​l​l​o​ ​{​n​a​m​e​}​!
	 * @param {string} name
	 */
	HI: RequiredParams<'name'>
	/**
	 * E​d​i​t​ ​s​r​c​/​A​p​p​.​t​s​x​ ​a​n​d​ ​s​a​v​e​ ​t​o​ ​r​e​l​o​a​d​.
	 */
	EDIT_AND_SAVE: string
	/**
	 * L​e​a​r​n​ ​E​x​p​o
	 */
	LEARN_EXPO: string
	/**
	 * Y​o​u​r​ ​n​a​m​e​:
	 */
	YOUR_NAME: string
	/**
	 * S​e​l​e​c​t​e​d​ ​l​o​c​a​l​e​:
	 */
	SELECTED_LOCALE: string
	/**
	 * T​o​d​a​y​ ​i​s​ ​{​d​a​t​e​|​w​e​e​k​d​a​y​}
	 * @param {Date} date
	 */
	TODAY: RequiredParams<'date|weekday'>
	/**
	 * Tab: Search
	 */
  SEARCH: string,
	/**
	 * Tab: Dashboard
	 */
  DASHBOARD: string,
	/**
	 * Tab: Menu
	 */
  MENU: string,
	/**
	 * Menu: Setting
	 */
  SETTING: string,
	/**
	 * Menu: Setting - Languages
	 */
  LANAGUAGES: string,
	/**
	 * Menu: Setting - Currencies
	 */
  CURRENCIES: string
}

export type TranslationFunctions = {
	/**
	 * choose locale...
	 */
	CHOOSE_LOCALE: () => LocalizedString
	/**
	 * Hello {name}!
	 */
	HI: (arg: { name: string }) => LocalizedString
	/**
	 * Edit src/App.tsx and save to reload.
	 */
	EDIT_AND_SAVE: () => LocalizedString
	/**
	 * Learn Expo
	 */
	LEARN_EXPO: () => LocalizedString
	/**
	 * Your name:
	 */
	YOUR_NAME: () => LocalizedString
	/**
	 * Selected locale:
	 */
	SELECTED_LOCALE: () => LocalizedString
	/**
	 * Today is {date|weekday}
	 */
	TODAY: (arg: { date: Date }) => LocalizedString
	/**
	 * Tab: Search
	 */
  SEARCH: () => LocalizedString,
	/**
	 * Tab: Dashboard
	 */
  DASHBOARD: () => LocalizedString,
	/**
	 * Tab: Menu
	 */
  MENU: () => LocalizedString,
	/**
	 * Menu: Setting
	 */
  SETTING: () => LocalizedString,
	/**
	 * Menu: Setting - Languages
	 */
  LANAGUAGES: () => LocalizedString,
	/**
	 * Menu: Setting - Currencies
	 */
  CURRENCIES: () => LocalizedString
}

export type Formatters = {
	weekday: (value: Date) => unknown
}
